[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_USE_YARN = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
