[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NEXT_TELEMETRY_DISABLED = "1"

# Simple redirect for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
